config/routes.rb
Rails.application.routes.draw do
  resources :room_events, only: [:index, :create, :show, :update, :edit, :destroy]
  get 'pages/about', as: "about"
  resources :rooms, only: [:index, :show] do
    resources :room_events, only: [:new]
  end
  #post '/room_events', to: redirect('/rooms/:id/room_events')
  root to: redirect('/rooms?locale=en')
  
  devise_for :users, :controllers => { :registrations => "registrations_mail" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room_event.rb
class RoomEvent < ApplicationRecord
  belongs_to :room
  belongs_to :user
  validates :frequency, inclusion: { in: ["Once", "DAILY", "WEEKLY"] }
  validates :description, length: {maximum: 200}, presence: true
  validates :room_id, :user_id, :interval, numericality: { only_integer: true, :greater_than_or_equal_to => 0}
  validates :start, :end, presence: true
  #, format: {with:/\A\d{2}:\d{2}\z/}
  #format: {with:/\A(\d){4}[01]\d[012]\dT[012]\d([0-6]\d){2}\z/}

end

app/controllers/room_events_controller.rb
class RoomEventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_room_event, only: [:show, :edit, :update, :destroy]
  # GET /room_events
  # GET /room_events.json
  def index
    @room_events = RoomEvent.all
  end

  # GET /room_events/1
  # GET /room_events/1.json
  def show
  end

  # GET /room_events/new
  def new
    @room_event = RoomEvent.new
   end

  # GET /room_events/1/edit
  def edit
  end

  # POST /room_events
  # POST /room_events.json
  def create
    #@room_event = RoomEvent.new(room_event_params.except(:day).except(:special_form))
    parameters =  room_event_params
    if parameters[:start].present? && parameters[:end].present? && parameters[:day].present?
      puts parameters[:start]
      starttime = (parameters[:day].gsub '-', '') + "T" + (parameters[:start].sub ':', '') + "00"
      endtime = (parameters[:day].gsub '-', '') + "T" + (parameters[:end].sub ':', '') + "00"
      parameters[:start] = starttime
      parameters[:end] = endtime
      #@room_event = RoomEvent.new(room_event_params.except(:day).except(:special_form))
    else 
      puts "fail"
      parameters[:start] = "0"
    end
    puts parameters[:start]
    @room_event = RoomEvent.new(parameters.except(:day).except(:locale).except(:special_form))
    respond_to do |format|
      if parameters[:special_form].present? && @room_event.save
        format.html { redirect_to @room_event, notice: 'Room event was successfully created.' }
        format.json { render :show, status: :created, location: @room_event }
      else 
        format.html { render :new }
	if @room_event.nil?
          format.json { render json: { message: "unprocessable_entity"} , status: :unprocessable_entity }
        else
	  format.json { render json: @room_event.errors , status: :unprocessable_entity }      
	end
      end
    end
  end

  # PATCH/PUT /room_events/1
  # PATCH/PUT /room_events/1.json
  def update
    parameters =  room_event_params
    if current_user.id != @room_event.user.id
      parameters[:user_id] = -1
    end
    if parameters[:start].present? && parameters[:end].present? && parameters[:day].present?
      parameters[:start] = (parameters[:day].gsub '-', '') + "T" + (parameters[:start].sub ':', '') + "00"
      parameters[:end] = (parameters[:day].gsub '-', '') + "T" + (parameters[:end].sub ':', '') + "00"
    else
      parameters[:start] = "0"
    end
    respond_to do |format|
      if @room_event.update(parameters.except(:day).except(:special_form))
        format.html { redirect_to @room_event, notice: 'Room event was successfully updated.' }
        format.json { render :show, status: :ok, location: @room_event }
      else
        format.html { render :edit }
        format.json { render json: @room_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_events/1
  # DELETE /room_events/1.json
  def destroy
    if current_user.id == @room_event.user.id
      @room_event.destroy!
      respond_to do |format|
        format.html { redirect_to room_events_url, notice: 'Room event was successfully destroyed.' }
        format.json { head :no_content }
    end

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_event
      @room_event = RoomEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_event_params
      params.require(:room_event).permit(:start, :end, :description, :room_id, :user_id, :day, :frequency, :interval, :special_form)
    end
end

app/helpers/room_events_helper.rb
module RoomEventsHelper
end

app/views/room_events/_form.html.erb
<%= form_with(model: room_event, local: true) do |form| %>
  <% if room_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room_event.errors.count, "error") %> prohibited this room_event from being saved:</h2>

      <ul>
        <% room_event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



<div class="field">
    <%= form.label t('Date') %>
    <%= form.date_field :day %>
</div>

  <div class="field">
    <%= form.label t('start') %>
    <%= form.time_field :start %>
  </div>

<div class="field">
    <%= form.label t('end') %>
    <%= form.time_field :end %>
  </div>


  <div class="field">
    <%= form.label t('description') %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :frequency, value: "Once" %>
    <%= form.hidden_field :interval, value: 0 %>
    <%= form.hidden_field :special_form, value: true %>
    <% if params[:room_id].present? %>
      <%= form.hidden_field :room_id, value: params[:room_id] %>
    <% else %>
      <%= form.hidden_field :room_id, value: @room_event.room_id %>
    <% end %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/room_events/edit.html.erb
<h1><%= t('title_edit_room_event') %></h1>

<%= render 'form', room_event: @room_event %>

<%= link_to t('show'), @room_event %> |
<%= link_to t('back'), room_events_path %>

app/views/room_events/index.html.erb
<h1><%=t('title_user')%></h1>
<table>
  <thead>
    <tr>
      <th><%=t('day')%></th>
      <th><%=t('start')%></th>
      <th><%=t('end')%></th>
      <th><%=t('description')%></th>
      <th><%=t('room')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user = User.where("email = ?", "admin@lsfraumsucher.htw").first %>
    <% @room_events.where.not(:user_id => @user.id).each do |room_event| %>
      <tr>
        <td>
                <% if room_event.frequency == "WEEKLY" || room_event.frequency == "Once" %>
                        <%= t(Date::DAYNAMES[Time.parse(room_event.start).wday].downcase) %>
                <% else %>
                        <% if room_event.frequency =="" %>
                                <%= t(Date::DAYNAMES[Time.parse(room_event.start).wday].downcase) %>
                        <% else %>
                                <%= t('room.events.'+room_event.frequency) %>
                        <% end %>
                <% end %>
        </td>
        <td><%= Time.parse(room_event.start).strftime("%H:%M") %></td>
        <td><%= Time.parse(room_event.end).strftime("%H:%M") %></td>
        <td><%= room_event.description %></td>
        <td><%= link_to room_event.room.campus + " " + room_event.room.building + " " + room_event.room.roomnr,  room_event.room %> </td>
        <td><%= link_to t('show'), room_event %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h1><%= t('title_htw') %></h1>
<table>
  <thead>
    <tr>	
      <th><%=t('day')%></th>
      <th><%=t('start')%></th>
      <th><%=t('end')%></th>
      <th><%=t('description')%></th>
      <th><%=t('room')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_events.where(:user_id => @user.id).each do |room_event| %>
      <tr>
        <td>
                <% if room_event.frequency == "WEEKLY" || room_event.frequency == "Once" %>
                        <%= t(Date::DAYNAMES[Time.parse(room_event.start).wday].downcase) %>
                <% else %>
                        <% if room_event.frequency =="" %>
                                <%= t(Date::DAYNAMES[Time.parse(room_event.start).wday].downcase) %>
                        <% else %>
                                <%= t('room.events.'+room_event.frequency) %>
                        <% end %>
                <% end %>
        </td>
        <td><%= Time.parse(room_event.start).strftime("%H:%M") %></td>
        <td><%= Time.parse(room_event.end).strftime("%H:%M") %></td>
        <td><%= room_event.description %></td>
        <td><%= link_to room_event.room.campus + " " + room_event.room.building + " " + room_event.room.roomnr,  room_event.room %> </td>
        <td><%= link_to t('show'), room_event %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/room_events/new.html.erb
<h1><%= t('title_new_room_event') %></h1>

<%= render 'form', room_event: @room_event %>

<%= link_to t('back'), :back %>

app/views/room_events/show.html.erb
<p>
  <strong><%=t('day')%>:</strong>
  <% if @room_event.frequency == "WEEKLY" || @room_event.frequency == "Once" %>
    <%= t(Date::DAYNAMES[Time.parse(@room_event.start).wday].downcase) %>
  <% else %>
    <% if @room_event.frequency =="" %>
      <%= t(Date::DAYNAMES[Time.parse(@room_event.start).wday].downcase) %>
    <% else %>
      <%= t('Mo-Fr') %>
    <% end %>
  <% end %>
</p>

<p>
  <strong><%=t('Date')%>:</strong>
  <%= Time.parse(@room_event.start).strftime("%d-%b-%Y")  %>
</p>

<p>
  <strong><%=t('start')%>:</strong>
  <%= Time.parse(@room_event.start).strftime("%H:%M")  %>
</p>

<p>
  <strong><%=t('end')%>:</strong>
  <%= Time.parse(@room_event.end).strftime("%H:%M")  %>
</p>

<p>
  <strong><%=t('description')%>:</strong>
  <%= @room_event.description %>
</p>

<p>
  <strong><%=t('room')%>:</strong>
  <%= @room_event.room.campus %> <%= @room_event.room.building %> <%= @room_event.room.roomnr %>
</p>

<p>
  <strong><%=t('user')%>:</strong>
  <%= @room_event.user.email %>
</p>

<% if !current_user.nil? && @room_event.user.id == current_user.id %>
  <%= link_to t('edit'), edit_room_event_path(@room_event) %> 
  <%= link_to t('delete'), room_event_path(@room_event), :confirm => "Are you sure?", :method => :delete %>
<% end %>
<%= link_to t('back'), room_events_path %>