config/routes.rb
Rails.application.routes.draw do
  resources :room_events, only: [:index, :create, :show, :update, :edit, :destroy]
  get 'pages/about', as: "about"
  resources :rooms, only: [:index, :show] do
    resources :room_events, only: [:new]
  end
  #post '/room_events', to: redirect('/rooms/:id/room_events')
  root to: redirect('/rooms?locale=en')
  
  devise_for :users, :controllers => { :registrations => "registrations_mail" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :room_events
    def self.search(roomtype, campus, day, starttime, endtime)
	paramsFound = false
	where = ""
	if roomtype || campus || day || starttime || endtime
		paramsFound = true
	end
	if roomtype 
	    where += "roomtype LIKE '" +"%#{roomtype}%" + "'"	
	end
	if campus && campus != "All"
	    if where != ""
	    	where += " AND "
	    end
	    where += "campus LIKE '" + "%#{campus}%" + "'"
	end
	if starttime && endtime
		if starttime == "" || endtime == ""
		
		else
		
			puts "starttime"
			puts starttime
			puts "endtime"
			puts endtime
			a = Room.where(where).order('campus DESC', :building, :roomnr)
			whereDaily = " frequency = 'DAILY'"
			eventStartsDuringTime1 = " TO_TIMESTAMP(start, 'YYYYMMDD-HH24MISS')::TIME >= '"+ starttime  +"'"
			eventStartsDuringTime2 = " TO_TIMESTAMP(start, 'YYYYMMDD-HH24MISS')::TIME < '"+ endtime  +"'"
			eventEndsDuringTime1 = " TO_TIMESTAMP(\"end\", 'YYYYMMDD-HH24MISS')::TIME <= '"+ endtime  +"'"
        	        puts "ok"
			eventEndsDuringTime2 = " TO_TIMESTAMP(\"end\", 'YYYYMMDD-HH24MISS')::TIME > '"+ starttime  +"'"
 			eventStartsBeforeTime = " TO_TIMESTAMP(start, 'YYYYMMDD-HH24MISS')::TIME < '"+ starttime  +"'"
			eventEndsAfterTime = " TO_TIMESTAMP(\"end\", 'YYYYMMDD-HH24MISS')::TIME > '"+ endtime  +"'"
		#whereEventStartBeforeStart = " TO_TIMESTAMP(start, 'YYYYMMDD-HH24MISS')::TIME >= '"+ starttime  +"'"
		#whereEventStartEnd = " TO_TIMESTAMP(start, 'YYYYMMDD-HH24MISS')::TIME < '"+ endtime  +"'"
		#whereEventEndAfterStartTime = " TO_TIMESTAMP(\"end\", 'YYYYMMDD-HH24MISS')::TIME <= '"+ endtime  +"'"
		#whereEndEnd = " TO_TIMESTAMP(\"end\", 'YYYYMMDD-HH24MISS')::TIME > '"+ starttime  +"'"
			whereSelectedDay = " EXTRACT(isodow FROM TO_TIMESTAMP(start, 'YYYYMMDD-HH24MISS')) = "
			whereSelectedDay += (Date.strptime(day,'%A').wday).to_s 
			daily_esdt = Room.joins(:room_events).where(whereDaily).where(eventStartsDuringTime1).where(eventStartsDuringTime2)
			esdt = Room.joins(:room_events).where(whereSelectedDay).where(eventStartsDuringTime1).where(eventStartsDuringTime2)	
			daily_eedt = Room.joins(:room_events).where(whereDaily).where(eventEndsDuringTime1).where(eventEndsDuringTime2)
	                eedt = Room.joins(:room_events).where(whereSelectedDay).where(eventEndsDuringTime1).where(eventEndsDuringTime2)
			daily_esbteat = Room.joins(:room_events).where(whereDaily).where(eventStartsBeforeTime).where(eventEndsAfterTime)
			esbteat =Room.joins(:room_events).where(whereSelectedDay).where(eventStartsBeforeTime).where(eventEndsAfterTime)
			return a-daily_esdt-esdt-daily_eedt-eedt-daily_esbteat-esbteat
		end
	end
	if day	
		if day.eql? "Montag"
	          day = "Monday"
		elsif day.eql? "Dienstag"
		  day = "Tuesday"
		elsif day.eql? "Mittwoch"
		  day = "Wednesday"
		elsif day.eql? "Donnerstag"
		  day = "Thursday"
		elsif day.eql? "Freitag"
		  day = "Friday"
                end 
		a = Room.where(where).order('campus DESC', :building, :roomnr)
		whereB = " EXTRACT(isodow FROM TO_TIMESTAMP(start, 'YYYYMMDD-HH24MISS')) = "
                whereB += (Date.strptime(day,'%A').wday).to_s
                whereC = " frequency = 'DAILY'"

		b = Room.joins(:room_events).where(whereB)
		c = Room.joins(:room_events).where(whereC)
		return a-b-c
#" AND (EXTRACT(isodow FROM TO_TIMESTAMP(start, 'YYYYMMDD-HH24MISS')) = 2 OR frequency = 'DAILY')"+                                                
#" GROUP BY rooms.id")
		
		#select = " SELECT rooms.id, rooms.roomtype, rooms.roomnr, rooms.building, rooms.campus, rooms.created_at, rooms.updated_at"
	 	#from = " FROM rooms, room_events"
		#where = " WHERE rooms.id = room_events.room_id" 
		#where += " AND EXTRACT(isodow FROM TO_TIMESTAMP(start, 'YYYYMMDD-HH24MISS')) !="
		#where += (Date.strptime(day,'%A').wday-1).to_s
		#where += " AND frequency != 'DAILY';"
		
		#return Room.ActiveRecord::Base.connection.execute(select + from + where)
	end		
	if !paramsFound
	    return all
	else
	    return where(where)
	end
    	
    end
end

app/controllers/rooms_controller.rb
require 'will_paginate/array'
class RoomsController < ApplicationController
	def index
		@rooms = Room.search(params[:roomtype], params[:campus], params[:day], params[:starttime], params[:endtime]).paginate(:per_page => 20, :page => params[:page])
		@room_events = RoomEvent.all()
	end
	def show
		@room = Room.find(params[:id])
		@room_events = @room.room_events
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_rooms.html.erb
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @rooms %>

app/views/rooms/index.html.erb
<h1><%= t('.listing_rooms') %></h1>


<%= form_tag rooms_path, :method => 'get', :id => "rooms_search" do %>
  <p>
    <div id="room_type_div">
      <%= label(:room, :roomtype, t('.room_type')) %>
      <%= text_field_tag :roomtype, params[:roomtype] %>
    </div>
    <div id="campus_div">
      <label for="campus"><%= t('.campus') %></label>
      <%= select_tag "campus", options_for_select(["WH", "TA", "PBH", "TGS"], :selected => params[:campus]), include_blank: "All"%>
    </div>
    <% dayOfWeek = [ t('.monday'), t('.tuesday'), t('.wednesday'), t('.thursday'), t('.friday')] %>
    <% wday = Date.today.wday %>
    <% if wday == 0 || wday == 6 %>
	<% wday = 0 %>
    <% else %>
	<% wday = wday-1 %> 
    <% end %>
    <div id="day_div">
      <label for="day"><%= t('.day_of_week') %></label>
      <%= select_tag "day", options_for_select(dayOfWeek, :selected => params[:day]) %>
    </div>
    <div id="startime_div">
      <label for="startime"><%= t('.start') %></label>
      <%= time_field_tag "starttime", nil, value: params[:starttime], min: '06:00', max:'21:30' %>
    </div>
    <div id="endtime_div">
      <label for="endtime"><%= t('.end') %></label>
      <%= time_field_tag "endtime", nil, value: params[:endtime], min: '06:30', max:'22:00' %>
    </div>
      <% if params.has_key?(:locale) %>
        <%= hidden_field_tag "locale", nil, value: params[:locale] %>
      <% else %>
        <% hidden_field_tag "locale", nil, value: 'en' %>
      <% end %>
    <%= submit_tag t('.search'), :name => nil %>
  </p>
<% end %>
 
<table>
  <tr>
    <th><%= t('.room_type') %></th>
    <th><%= t('.room') %></th>
    <th><%= t('.building') %></th>
    <th><%= t('.campus') %></th>
  </tr>
  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.roomtype %></td>
      <td><%= room.roomnr %></td>
      <td><%= room.building %></td>
      <td><%= room.campus %></td>
      <td><%= link_to t('.show'), room_path(room) %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @rooms %>

app/views/rooms/index.js.erb
$("#rooms").html("<%= escape_javascript(render("rooms")) %>");

app/views/rooms/show.html.erb
<%= stylesheet_link_tag "rooms" %>
<p>
  <strong><%= t('room_type') %>:</strong>
  <%= @room.roomtype %>
</p>
<p>
  <strong><%= t('room') %>:</strong>
  <%= @room.roomnr %>
</p>
<p>
  <strong><%= t('building') %>:</strong>
  <%= @room.building %>
</p>
<p>
  <strong><%= t('campus') %>:</strong>
  <%= @room.campus %>
</p>

<h1><%= t('room_events') %></h1>
<table>
  <thead>
    <tr>
      <th><%= t('day') %></th>
      <th><%= t('start') %></th>
      <th><%= t('end') %></th>
      <th><%= t('description') %></th>
      <th><%= t('room') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @room_events.each do |room_event| %>
      <tr>
        <td>
		<% if room_event.frequency == "WEEKLY" || room_event.frequency == "Once" %>
                        <%= t(Date::DAYNAMES[Time.parse(room_event.start).wday].downcase) %>
                <% else %>
                        <% if room_event.frequency =="" %>
                                <%= t(Date::DAYNAMES[Time.parse(room_event.start).wday].downcase) %>
                        <% else %>
                                <%= t('Mo_Fr') %>
                        <% end %>
                <% end %>
        </td>
        <td><%= Time.parse(room_event.start).strftime("%H:%M") %></td>
        <td><%= Time.parse(room_event.end).strftime("%H:%M") %></td>
        <td><%= room_event.description %></td>
        <td><%= room_event.room.campus %> <%= room_event.room.building %> <%= room_event.room.roomnr %>
        <td><%= link_to t('show'), room_event %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<td><%= link_to t('new_room_event'), new_room_room_event_path(:room_id => @room.id) %></td>