config/routes.rb
Rails.application.routes.draw do
  resources :room_events, only: [:index, :create, :show, :update, :edit, :destroy]
  get 'pages/about', as: "about"
  resources :rooms, only: [:index, :show] do
    resources :room_events, only: [:new]
  end
  #post '/room_events', to: redirect('/rooms/:id/room_events')
  root to: redirect('/rooms?locale=en')
  
  devise_for :users, :controllers => { :registrations => "registrations_mail" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
	<!DOCTYPE html>
<html>
  <head>
    <title>Lsfraumsucher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "rooms" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to t('nav.title'), rooms_path %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
	   <li><%= link_to t('nav.rooms'), rooms_path %></li>
           <li><%= link_to t('nav.events'), room_events_path %></li>
           <li><%= link_to t('nav.about'), about_path %></li>
          </ul>
	  <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            <%= t('nav.logged') %> <strong><%= current_user.email %></strong>.
            <%= link_to t('nav.edit'), edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to t('nav.logout'), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to t('nav.sign_up'), new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to t('nav.login'), new_user_session_path, :class => 'navbar-link'  %>
          <% end %> 
          </p>
          <p class ="navbar-text pull-right">
            <%= link_to "English", {locale: :en}%>
            <%= link_to "Deutsch", {locale: :de}%>
          </p>
        </div>
      </div>
    </nav>
    <% if notice %>
	<p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
        <%= yield %>
    </div>
  </body>
  <footer>
    <div class="container">
      LSF Raumsucher made by Meron & Levent <%= Time.now.year %>
    </div>
  </footer>
</html>